### ISSUE TITLE
你好 验证码404

### ISSUE THREAD

**Issue by 481617494** [ccenote/ccenote-blog-admin#1]
我使用postman访问http://localhost:8098/api/back/admin/getVerifyCode得到的内容是![image](https://github.com/ccenote/ccenote-blog-admin/assets/67628262/bcadc83b-cec1-4971-9441-c8017f77cb00)图片的内容是
![image](https://github.com/ccenote/ccenote-blog-admin/assets/67628262/600ea740-dabb-4fb2-9622-e92a8bb84884)
怎么解决啊

**Comment by 481617494** [comment]
验证码没问题

**Comment by jince-boy** [comment]
请问您有开始redis吗

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月29日 12:29 |
| 收件人 | ccenote/ccenote-blog-admin ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | Re: [ccenote/ccenote-blog-admin] 你好 验证码404 (Issue #1) |

验证码没问题
